services:
  app:
    container_name: mana-ai
    #image: m4rkus28/mana-ai:latest
    build:
      context: .
      dockerfile: Dockerfile
    # Define variable
    environment:
      - WORKERS=1
    volumes:
      - ./dev-poet-461212-d9-35a36f7ab681.json:/home/app/web/dev-poet-461212-d9-35a36f7ab681.json:ro
    ports:
      - "8127:8000"
    env_file:
      - ./.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  chroma-data:
    driver: local
